blank_issues_enabled: false

newPRWelcomeComment: >
  Thanks for submitting an application and welcome to Slingshot!

  Our team will validate your entry for completeness and invite our community panel for a final review, to help us process this quickly please ensure all questions are filled out and complete.
